# Generated by Django 5.1.3 on 2024-11-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_shippingaddress_shipping_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_address2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
